name: Useful-Commands
version: 1.2
author: Phoenix_PassiHD
main: de.phoenixts.phoenix.Main

commands:
  team:
    aliases: [staff]
  teamspeak:
    aliases: [ts]
  discord:
    aliases: [dc]
  bier:
    aliases: [saufen]