name: Useful-Commands
version: 1.6
author: Phoenix_PassiHD
main: de.phoenixts.phoenix.Main

commands:
  team:
    aliases: [staff]
  teamspeak:
    aliases: [ts]
  discord:
    aliases: [dc]
  bier:
    aliases: [saufen]
  fly:
    aliases: [Fliegen]
  feed:
    aliases: [Futter]