Team_message: '&eDu willst dem Team joinen? Bewirb dich jetzt bei uns, via Minecraft Chat, oder E-Mail.'
# Leg die Nachricht fest, die der Spieler erhält.

TeamSpeak_message: '&bUnser TeamSpeak Server: Server.de'
# Leg die Nachricht fest, die der Spieler erhält.

Discord_message: '&aUnser Discord: DeinDiscord'
# Leg die Nachricht fest, die der Spieler erhält.

no_perm: '&cDu bist nicht berechtigt diesen Befehl auszuführen'
# Leg die Nachricht fest, die ein Spieler ohne Berechtigung erhält

no_console: '&cNur Spieler können diesen Befehl ausführen'
# Leg die Nachricht fest, die in der Konsole erscheint, beim ausführen des Befehls in der Konsole

# Farbcodes kann man mit '&' verwenden.

team_permission: 'team.use'
# Leg die benötigte Berechtigung für /team fest.

teamspeak_permission: 'teamspeak.use'
# Leg die benötigte Berechtigung für /teamspeak fest.

discord_permission: 'dc.use'
# Leg die benötigte Berechtigung für /discord fest.

bier_permission: 'bier.use'
# Leg die benötigte Berechtigung für /bier fest.

First_JoinMessage: '&a&l<player> &b&list dem Server das erste Mal beigetreten.'
# Lege die Nachricht fest, die eim erstmaligen Joinen eines Spielers erscheint.

JoinMessage: '&e&l<player> &6&list dem Server beigetreten.'
# Lege die Nachricht fest, die erscheint, wenn ein Spieler joint.

QuitMessage: '&2&l<player> &f&list offline gegangen.'
# Lege die Nachricht fest, die erscheint, wenn ein Spieler den Server verlässt.

Bier_Message: '&cNich so viel trinken...'
# Nich so viel trinken...